export const categories = {
  "cm": "Concert : Musique actuelle (Pop, Rock, Electro, Reggae….)",
  "cv": "Concert : Variétés",
  "cc": "Concert : Classique (Opéra, Symphonique, Lyrique, …)",
  "cj": "Concert : Jazz – Blues",
  "fe": "Festival",
  "co": "Comédie musicale, music-hall",
  "th": "Pièce de théâtre",
  "om": "One man show",
  "sp": "Spectacle pour enfant",
  "ci": "Cirque",
  "sr": "Sport : Rugby",
  "sf": "Sport : Football",
  "sa": "Sport : Athlétisme",
  "ss": "Sport : Sports automobiles",
  "st": "Sport : Tournoi sportif",
  "ec": "Evénement professionnel : Congrès",
  "es": "Evénement professionnel : Séminaire",
  "eh": "Evénement professionnel : Showcase",
  "au": "Autre",
};


export const types = {
  "du": "Date unique",
  "dm": "Dates multiples",
  "pf": "Plateau artistique/Festival",
  "to": "Tournée",
}


export const scenes = {
  // "esd": "Exterieur : Scène découverte",
  // "esc": "Exterieur : Scène couverte",
  // "es3": "Exterieur : Scène couvert + 3 côtés",
  // "esl": "Exterieur : Sous chapiteau ou structure légère",
  // "epa": "Exterieur : Plein air total",
  // "sal": "Salle",
  // "feu": "Feu d’artifice",
  "esd": "Scène découverte",
  "esc": "Scène couverte",
  "es3": "Scène couverte + 3 cotés",
  "esl": "Sous Chapiteau ou structure légère",
  "epa": "Plein air total",
  "sal": "Salle / Lieu fermé",
  "feu": "Feux d'artifice",

}


export const damageBasises = {
  // "dpfe": "Date produite : Frais engages",
  // "dpfb": "Date produite : Frais + bénéfices",
  // "dpre": "Date produite : Recette",
  // "dcca": "Date co-réalisée : Contrat avec minimum garantie",
  // "dvcv": "Date vendue : Contrat de vente",
  // "dvcp": "Date vendue : Coût du plateau",
  "dpfe": "FRAIS ENGAGÉS",
  "dpfb": "FRAIS + BÉNÉFICES",
  "dpre": "RECETTE",
  "dcca": "CONTRAT / MINIMUM GARANTI",
  "dvcv": "CONTRAT DE VENTE",
  "dvcp": "COÛT DU PLATEAU",
}


export const countries = {
  // "AF": "Afghanistan",
  // "AX": "Åland Islands",
  // "AL": "Albania",
  // "DZ": "Algeria",
  // "AS": "American Samoa",
  // "AD": "Andorra",
  // "AO": "Angola",
  // "AI": "Anguilla",
  // "AQ": "Antarctica",
  // "AG": "Antigua and Barbuda",
  // "AR": "Argentina",
  // "AM": "Armenia",
  // "AW": "Aruba",
  // "AU": "Australia",
  // "AT": "Austria",
  // "AZ": "Azerbaijan",
  // "BS": "Bahamas",
  // "BH": "Bahrain",
  // "BD": "Bangladesh",
  // "BB": "Barbados",
  // "BY": "Belarus",
  // "BE": "Belgium",
  // "BZ": "Belize",
  // "BJ": "Benin",
  // "BM": "Bermuda",
  // "BT": "Bhutan",
  // "BO": "Bolivia",
  // "BA": "Bosnia and Herzegovina",
  // "BW": "Botswana",
  // "BV": "Bouvet Island",
  // "BR": "Brazil",
  // "IO": "British Indian Ocean Territory",
  // "BN": "Brunei Darussalam",
  // "BG": "Bulgaria",
  // "BF": "Burkina Faso",
  // "BI": "Burundi",
  // "KH": "Cambodia",
  // "CM": "Cameroon",
  // "CA": "Canada",
  // "CV": "Cape Verde",
  // "KY": "Cayman Islands",
  // "CF": "Central African Republic",
  // "TD": "Chad",
  // "CL": "Chile",
  // "CN": "China",
  // "CX": "Christmas Island",
  // "CC": "Cocos (Keeling) Islands",
  // "CO": "Colombia",
  // "KM": "Comoros",
  // "CG": "Congo",
  // "CD": "Congo, The Democratic Republic of the",
  // "CK": "Cook Islands",
  // "CR": "Costa Rica",
  // "CI": "Cote D'Ivoire",
  // "HR": "Croatia",
  // "CU": "Cuba",
  // "CY": "Cyprus",
  // "CZ": "Czech Republic",
  // "DK": "Denmark",
  // "DJ": "Djibouti",
  // "DM": "Dominica",
  // "DO": "Dominican Republic",
  // "EC": "Ecuador",
  // "EG": "Egypt",
  // "SV": "El Salvador",
  // "GQ": "Equatorial Guinea",
  // "ER": "Eritrea",
  // "EE": "Estonia",
  // "ET": "Ethiopia",
  // "FK": "Falkland Islands (Malvinas)",
  // "FO": "Faroe Islands",
  // "FJ": "Fiji",
  // "FI": "Finland",
  // "FR": "France",
  // "GF": "French Guiana",
  // "PF": "French Polynesia",
  // "TF": "French Southern Territories",
  // "GA": "Gabon",
  // "GM": "Gambia",
  // "GE": "Georgia",
  // "DE": "Germany",
  // "GH": "Ghana",
  // "GI": "Gibraltar",
  // "GR": "Greece",
  // "GL": "Greenland",
  // "GD": "Grenada",
  // "GP": "Guadeloupe",
  // "GU": "Guam",
  // "GT": "Guatemala",
  // "GG": "Guernsey",
  // "GN": "Guinea",
  // "GW": "Guinea-Bissau",
  // "GY": "Guyana",
  // "HT": "Haiti",
  // "HM": "Heard Island and Mcdonald Islands",
  // "VA": "Holy See (Vatican City State)",
  // "HN": "Honduras",
  // "HK": "Hong Kong",
  // "HU": "Hungary",
  // "IS": "Iceland",
  // "IN": "India",
  // "ID": "Indonesia",
  // "IR": "Iran, Islamic Republic Of",
  // "IQ": "Iraq",
  // "IE": "Ireland",
  // "IM": "Isle of Man",
  // "IL": "Israel",
  // "IT": "Italy",
  // "JM": "Jamaica",
  // "JP": "Japan",
  // "JE": "Jersey",
  // "JO": "Jordan",
  // "KZ": "Kazakhstan",
  // "KE": "Kenya",
  // "KI": "Kiribati",
  // "KP": "Democratic People's Republic of Korea",
  // "KR": "Korea, Republic of",
  // "XK": "Kosovo",
  // "KW": "Kuwait",
  // "KG": "Kyrgyzstan",
  // "LA": "Lao People's Democratic Republic",
  // "LV": "Latvia",
  // "LB": "Lebanon",
  // "LS": "Lesotho",
  // "LR": "Liberia",
  // "LY": "Libyan Arab Jamahiriya",
  // "LI": "Liechtenstein",
  // "LT": "Lithuania",
  // "LU": "Luxembourg",
  // "MO": "Macao",
  // "MK": "Macedonia, The Former Yugoslav Republic of",
  // "MG": "Madagascar",
  // "MW": "Malawi",
  // "MY": "Malaysia",
  // "MV": "Maldives",
  // "ML": "Mali",
  // "MT": "Malta",
  // "MH": "Marshall Islands",
  // "MQ": "Martinique",
  // "MR": "Mauritania",
  // "MU": "Mauritius",
  // "YT": "Mayotte",
  // "MX": "Mexico",
  // "FM": "Micronesia, Federated States of",
  // "MD": "Moldova, Republic of",
  // "MC": "Monaco",
  // "MN": "Mongolia",
  // "ME": "Montenegro",
  // "MS": "Montserrat",
  // "MA": "Morocco",
  // "MZ": "Mozambique",
  // "MM": "Myanmar",
  // "NA": "Namibia",
  // "NR": "Nauru",
  // "NP": "Nepal",
  // "NL": "Netherlands",
  // "AN": "Netherlands Antilles",
  // "NC": "New Caledonia",
  // "NZ": "New Zealand",
  // "NI": "Nicaragua",
  // "NE": "Niger",
  // "NG": "Nigeria",
  // "NU": "Niue",
  // "NF": "Norfolk Island",
  // "MP": "Northern Mariana Islands",
  // "NO": "Norway",
  // "OM": "Oman",
  // "PK": "Pakistan",
  // "PW": "Palau",
  // "PS": "Palestinian Territory, Occupied",
  // "PA": "Panama",
  // "PG": "Papua New Guinea",
  // "PY": "Paraguay",
  // "PE": "Peru",
  // "PH": "Philippines",
  // "PN": "Pitcairn",
  // "PL": "Poland",
  // "PT": "Portugal",
  // "PR": "Puerto Rico",
  // "QA": "Qatar",
  // "RE": "Reunion",
  // "RO": "Romania",
  // "RU": "Russian Federation",
  // "RW": "Rwanda",
  // "SH": "Saint Helena",
  // "KN": "Saint Kitts and Nevis",
  // "LC": "Saint Lucia",
  // "PM": "Saint Pierre and Miquelon",
  // "VC": "Saint Vincent and the Grenadines",
  // "WS": "Samoa",
  // "SM": "San Marino",
  // "ST": "Sao Tome and Principe",
  // "SA": "Saudi Arabia",
  // "SN": "Senegal",
  // "RS": "Serbia",
  // "SC": "Seychelles",
  // "SL": "Sierra Leone",
  // "SG": "Singapore",
  // "SK": "Slovakia",
  // "SI": "Slovenia",
  // "SB": "Solomon Islands",
  // "SO": "Somalia",
  // "ZA": "South Africa",
  // "GS": "South Georgia and the South Sandwich Islands",
  // "ES": "Spain",
  // "LK": "Sri Lanka",
  // "SD": "Sudan",
  // "SR": "Suriname",
  // "SJ": "Svalbard and Jan Mayen",
  // "SZ": "Swaziland",
  // "SE": "Sweden",
  // "CH": "Switzerland",
  // "SY": "Syrian Arab Republic",
  // "TW": "Taiwan",
  // "TJ": "Tajikistan",
  // "TZ": "Tanzania, United Republic of",
  // "TH": "Thailand",
  // "TL": "Timor-Leste",
  // "TG": "Togo",
  // "TK": "Tokelau",
  // "TO": "Tonga",
  // "TT": "Trinidad and Tobago",
  // "TN": "Tunisia",
  // "TR": "Turkey",
  // "TM": "Turkmenistan",
  // "TC": "Turks and Caicos Islands",
  // "TV": "Tuvalu",
  // "UG": "Uganda",
  // "UA": "Ukraine",
  // "AE": "United Arab Emirates",
  // "GB": "United Kingdom",
  // "US": "United States",
  // "UM": "United States Minor Outlying Islands",
  // "UY": "Uruguay",
  // "UZ": "Uzbekistan",
  // "VU": "Vanuatu",
  // "VE": "Venezuela",
  // "VN": "Viet Nam",
  // "VG": "Virgin Islands, British",
  // "VI": "Virgin Islands, U.S.",
  // "WF": "Wallis and Futuna",
  // "EH": "Western Sahara",
  // "YE": "Yemen",
  // "ZM": "Zambia",
  // "ZW": "Zimbabwe"

  'FR': 'FRANCE',
  'AF': 'AFGHANISTAN',
  'ZA': 'AFRIQUE DU SUD',
  'AX': 'ÅLAND, ÎLES',
  'AL': 'ALBANIE',
  'DZ': 'ALGERIE',
  'DE': 'ALLEMAGNE',
  'AD': 'ANDORRE',
  'AO': 'ANGOLA',
  'AI': 'ANGUILLA',
  'AQ': 'ANTARCTIQUE',
  'AG': 'ANTIGUA ET BARBUDA',
  'SA': 'ARABIE SAOUDITE',
  'AR': 'ARGENTINE',
  'AM': 'ARMENIE',
  'AW': 'ARUBA',
  'AU': 'AUSTRALIE',
  'AT': 'AUTRICHE',
  'AZ': 'AZERBAIDJAN',
  'BS': 'BAHAMAS',
  'BH': 'BAHREIN',
  'BD': 'BANGLADESH',
  'BB': 'BARBADE',
  'BY': 'BELARUS',
  'BE': 'BELGIQUE',
  'BZ': 'BELIZE',
  'BJ': 'BENIN',
  'BM': 'BERMUDES',
  'BT': 'BHOUTAN',
  'BO': 'BOLIVIE, l\'ETAT PLURINATIONAL DE',
  'BQ': 'BONAIRE, SAINT-EUSTACHE ET SABA',
  'BA': 'BOSNIE-HERZEGOVINE',
  'BW': 'BOTSWANA',
  'BV': 'BOUVET, ILE',
  'BR': 'BRESIL',
  'BN': 'BRUNEI DARUSSALAM',
  'BG': 'BULGARIE',
  'BF': 'BURKINA FASO',
  'BI': 'BURUNDI',
  'KY': 'CAIMANES, ILES',
  'KH': 'CAMBODGE',
  'CM': 'CAMEROUN',
  'CA': 'CANADA',
  'CV': 'CAP-VERT',
  'CF': 'CENTRAFRICAINE, REPUBLIQUE',
  'CL': 'CHILI',
  'CN': 'CHINE',
  'CX': 'CHRISTMAS, ILE',
  'CY': 'CHYPRE',
  'CC': 'COCOS (KEELING), ILES',
  'CO': 'COLOMBIE',
  'KM': 'COMORES',
  'CG': 'CONGO',
  'CD': 'CONGO, LA REPUBLIQUE DEMOCRATIQUE DU',
  'CK': 'COOK, ILES',
  'KR': 'COREE, REPUBLIQUE DE',
  'KP': 'COREE, REPUBLIQUE POPULAIRE DEMOCRATIQUE DE',
  'CR': 'COSTA RICA',
  'CI': 'COTE D\'IVOIRE',
  'HR': 'CROATIE',
  'CU': 'CUBA',
  'CW': 'CURACAO',
  'DK': 'DANEMARK',
  'DJ': 'DJIBOUTI',
  'DO': 'DOMINICAINE, REPUBLIQUE',
  'DM': 'DOMINIQUE',
  'EG': 'EGYPTE',
  'SV': 'EL SALVADOR',
  'AE': 'EMIRATS ARABES UNIS',
  'EC': 'EQUATEUR',
  'ER': 'ERYTHREE',
  'ES': 'ESPAGNE',
  'EE': 'ESTONIE',
  'US': 'ETATS-UNIS',
  'ET': 'ETHIOPIE',
  'FK': 'FALKLAND, ILES (MALVINAS)',
  'FO': 'FEROE, ILES',
  'FJ': 'FIDJI',
  'FI': 'FINLANDE',
  'GA': 'GABON',
  'GM': 'GAMBIE',
  'GE': 'GEORGIE',
  'GS': 'GEORGIE DU SUD ET LES ILES SANDWICH DU SUD',
  'GH': 'GHANA',
  'GI': 'GIBRALTAR',
  'GR': 'GRECE',
  'GD': 'GRENADE',
  'GL': 'GROENLAND',
  'GP': 'GUADELOUPE',
  'GU': 'GUAM',
  'GT': 'GUATEMALA',
  'GG': 'GUERNESEY',
  'GN': 'GUINEE',
  'GQ': 'GUINEE EQUATORIALE',
  'GW': 'GUINEE-BISSAU',
  'GY': 'GUYANA',
  'GF': 'GUYANE FRANCAISE',
  'HT': 'HAITI',
  'HM': 'HEARD, ILE ET MCDONALD, ILES',
  'HN': 'HONDURAS',
  'HK': 'HONG KONG',
  'HU': 'HONGRIE',
  'IM': 'ILE DE MAN',
  'UM': 'ILES MINEURES ELOIGNEES DES ETATS-UNIS',
  'VG': 'ILES VIERGES BRITANNIQUES',
  'VI': 'ILES VIERGES DES ETATS-UNIS',
  'IN': 'INDE',
  'ID': 'INDONESIE',
  'IR': 'IRAN, REPUBLIQUE ISLAMIQUE D\'',
  'IQ': 'IRAQ',
  'IE': 'IRLANDE',
  'IS': 'ISLANDE',
  'IL': 'ISRAEL',
  'IT': 'ITALIE',
  'JM': 'JAMAIQUE',
  'JP': 'JAPON',
  'JE': 'JERSEY',
  'JO': 'JORDANIE',
  'KZ': 'KAZAKHSTAN',
  'KE': 'KENYA',
  'KG': 'KIRGHIZISTAN',
  'KI': 'KIRIBATI',
  'KW': 'KOWEIT',
  'LA': 'LAO, REPUBLIQUE DEMOCRATIQUE POPULAIRE',
  'LS': 'LESOTHO',
  'LV': 'LETTONIE',
  'LB': 'LIBAN',
  'LR': 'LIBERIA',
  'LY': 'LIBYENNE, JAMAHIRIYA ARABE',
  'LI': 'LIECHTENSTEIN',
  'LT': 'LITUANIE',
  'LU': 'LUXEMBOURG',
  'MO': 'MACAO',
  'MK': 'MACEDOINE, L\'EX-REPUBLIQUE YOUGOSLAVE DE',
  'MG': 'MADAGASCAR',
  'MY': 'MALAISIE',
  'MW': 'MALAWI',
  'MV': 'MALDIVES',
  'ML': 'MALI',
  'MT': 'MALTE',
  'MP': 'MARIANNES DU NORD, ILES',
  'MA': 'MAROC',
  'MH': 'MARSHALL, ILES',
  'MQ': 'MARTINIQUE',
  'MU': 'MAURICE',
  'MR': 'MAURITANIE',
  'YT': 'MAYOTTE',
  'MX': 'MEXIQUE',
  'FM': 'MICRONESIE, ETATS FEDERES DE',
  'MD': 'MOLDOVA, REPUBLIQUE DE',
  'MC': 'MONACO',
  'MN': 'MONGOLIE',
  'ME': 'MONTENEGRO',
  'MS': 'MONTSERRAT',
  'MZ': 'MOZAMBIQUE',
  'MM': 'MYANMAR',
  'NA': 'NAMIBIE',
  'NR': 'NAURU',
  'NP': 'NEPAL',
  'NI': 'NICARAGUA',
  'NE': 'NIGER',
  'NG': 'NIGERIA',
  'NU': 'NIUE',
  'NF': 'NORFOLK, ILE',
  'NO': 'NORVEGE',
  'NC': 'NOUVELLE-CALEDONIE',
  'NZ': 'NOUVELLE-ZELANDE',
  'IO': 'OCEAN INDIEN, TERRITOIRE BRITANNIQUE DE L\'',
  'OM': 'OMAN',
  'UG': 'OUGANDA',
  'UZ': 'OUZBEKISTAN',
  'PK': 'PAKISTAN',
  'PW': 'PALAOS',
  'PS': 'PALESTINIEN OCCUPE, TERRITOIRE',
  'PA': 'PANAMA',
  'PG': 'PAPOUASIE-NOUVELLE-GUINEE',
  'PY': 'PARAGUAY',
  'NL': 'PAYS-BAS',
  'PE': 'PEROU',
  'PH': 'PHILIPPINES',
  'PN': 'PITCAIRN',
  'PL': 'POLOGNE',
  'PF': 'POLYNESIE FRANCAISE',
  'PR': 'PORTO RICO',
  'PT': 'PORTUGAL',
  'QA': 'QATAR',
  'RE': 'REUNION',
  'RO': 'ROUMANIE',
  'GB': 'ROYAUME-UNI',
  'RU': 'RUSSIE, FEDERATION DE',
  'RW': 'RWANDA',
  'EH': 'SAHARA OCCIDENTAL',
  'BL': 'SAINT-BARTHELEMY',
  'KN': 'SAINT-KITTS-ET-NEVIS',
  'SM': 'SAINT-MARIN',
  'MF': 'SAINT-MARTIN (PARTIE FRANCAISE)',
  'SX': 'SAINT-MARTIN (PARTIE NEERLANDAISE)',
  'PM': 'SAINT-PIERRE-ET-MIQUELON',
  'VA': 'SAINT-SIEGE (ETAT DE LA CITE DU VATICAN)',
  'VC': 'SAINT-VINCENT-ET-LES GRENADINES',
  'SH': 'SAINTE-HELENE, ASCENSION ET TRISTAN DA CUNHA',
  'LC': 'SAINTE-LUCIE',
  'SB': 'SALOMON, ILES',
  'WS': 'SAMOA',
  'AS': 'SAMOA AMERICAINES',
  'ST': 'SAO TOME-ET-PRINCIPE',
  'SN': 'SENEGAL',
  'RS': 'SERBIE',
  'SC': 'SEYCHELLES',
  'SL': 'SIERRA LEONE',
  'SG': 'SINGAPOUR',
  'SK': 'SLOVAQUIE',
  'SI': 'SLOVENIE',
  'SO': 'SOMALIE',
  'SD': 'SOUDAN',
  'LK': 'SRI LANKA',
  'SE': 'SUEDE',
  'CH': 'SUISSE',
  'SR': 'SURINAME',
  'SJ': 'SVALBARD ET ILE JAN MAYEN',
  'SZ': 'SWAZILAND',
  'SY': 'SYRIENNE, REPUBLIQUE ARABE',
  'TJ': 'TADJIKISTAN',
  'TW': 'TAIWAN, PROVINCE DE CHINE',
  'TZ': 'TANZANIE, REPUBLIQUE-UNIE DE',
  'TD': 'TCHAD',
  'CZ': 'TCHEQUE, REPUBLIQUE',
  'TF': 'TERRES AUSTRALES FRANCAISES',
  'TH': 'THAILANDE',
  'TL': 'TIMOR-LESTE',
  'TG': 'TOGO',
  'TK': 'TOKELAU',
  'TO': 'TONGA',
  'TT': 'TRINITE-ET-TOBAGO',
  'TN': 'TUNISIE',
  'TM': 'TURKMENISTAN',
  'TC': 'TURKS ET CAIQUES, ILES',
  'TR': 'TURQUIE',
  'TV': 'TUVALU',
  'UA': 'UKRAINE',
  'UY': 'URUGUAY',
  'VU': 'VANUATU',
  'VE': 'VENEZUELA, REPUBLIQUE BOLIVARIENNE DU',
  'VN': 'VIET NAM',
  'WF': 'WALLIS ET FUTUNA',
  'YE': 'YEMEN',
  'ZM': 'ZAMBIE',
  'ZW': 'ZIMBABWE',
}


const list2Array = (list) =>
  Object.keys(list).map(
    key => {
      return { key: key, value: list[key] }
    }
  );


export const categoriesArray = ( () => list2Array(categories))();
export const typesArray = ( () => list2Array(types))();
export const scenesArray = ( () => list2Array(scenes))();
export const damageBasisesArray = ( () => list2Array(damageBasises))();
export const countriesArray = ( () => list2Array(countries))();


export default {
  categories,
  types,
  scenes,
  damageBasises,
  countries
}

export const arrays = {
  categories: categoriesArray,
  types: typesArray,
  scenes: scenesArray,
  damageBasises: damageBasisesArray,
  countries: countriesArray,
}
